version: '3.8'

services:
  # DATABASE
  db-founderdash:
    image: postgres:15-alpine
    container_name: founderdash_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Diva@2004}
      POSTGRES_DB: ${POSTGRES_DB:-founderdash_db}
    ports:
      - "5439:5432"
    volumes:
      - postgres_data_founderdash:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # BACKEND
  backend-founderdash:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: founderdash_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:Diva%402004@db-founderdash:5432/founderdash_db
    ports:
      - "8008:8000"
    depends_on:
      db-founderdash:
        condition: service_healthy

  # FRONTEND
  frontend-founderdash:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8008
    container_name: founderdash_frontend
    ports:
      - "3007:80"
    depends_on:
      - backend-founderdash

volumes:
  postgres_data_founderdash:
